version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: PG2123456
      MYSQL_DATABASE: eve_personal
    ports:
      - "33060:3306"
    # Opcional: Montar una carpeta para almacenar los datos de MySQL en el host
    volumes:
      - ./mysql-data:/var/lib/mysql
    # Opcional: Si tienes scripts SQL para inicializar la base de datos, colócalos en la carpeta db-scripts
    # Esto copiará los scripts al directorio /docker-entrypoint-initdb.d/ en el contenedor
    # volumes:
    #   - ./db-scripts:/docker-entrypoint-initdb.d/
