version: '3.8'

services:
  # application:
  #   build: .
  #   ports:
  #     - "9200:9200"
  #   depends_on:
  #     - database
  database:
    image: mysql:latest
    container_name: mysql-db-eve-personal
    environment:
      MYSQL_ROOT_PASSWORD: PG2123456
      MYSQL_DATABASE: eve_personal
    ports:
      - "33060:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
   
